/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calis1;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Brith
 */
public class iniciar_sesion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(iniciar_sesion.class.getName());

    /**
     * Creates new form iniciar_sesion
     */
    public iniciar_sesion() {
   initComponents();
        this.setSize(800, 600);
        
        // --- CARGA DIRECTA EN EL COMPONENTE DEL DISEÑADOR ---
        try {
            // Buscamos la imagen en tus recursos de Maven
            // (Nota: cambiaste el nombre a "icono.jpeg" en tu último código, asegúrate de que se llame así)
            java.net.URL rutaImg = getClass().getResource("/imagenes/icono.jpeg");
            
            if (rutaImg != null) {
                ImageIcon iconoOriginal = new ImageIcon(rutaImg);
                // Le pasamos la imagen al objeto que ya existe en tu pantalla de NetBeans
                panelredondo1.setImage(iconoOriginal.getImage());
                System.out.println("✅ Imagen asignada con éxito a panelredondo1");
            } else {
                System.out.println("❌ ERROR: No se encontró el archivo en /imagenes/icono.jpeg");
            }
        } catch (Exception e) {
            System.out.println("Error al cargar la imagen: " + e.getMessage());
        }
//this.getContentPane().remove(jPanel3);

// 2. Crear tu panel redondo personalizado
jPanel3 = new panelredondo();

// 3. Forzar AbsoluteLayout en la ventana
org.netbeans.lib.awtextra.AbsoluteLayout layout = new org.netbeans.lib.awtextra.AbsoluteLayout();
this.getContentPane().setLayout(layout);

// 4. Crear los parámetros de posición exactos que AbsoluteLayout exige
// (X, Y, Ancho, Alto) -> Ponemos 250 y 250 para que sea un círculo perfecto
org.netbeans.lib.awtextra.AbsoluteConstraints constraints = new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 120, 250, 250);

// 5. Añadir el nuevo círculo pasándole sus coordenadas exactas
this.getContentPane().add(jPanel3, constraints);

// 6. Refrescar la pantalla
this.revalidate();
this.repaint();

        jButton1.setPreferredSize(new java.awt.Dimension(42, 42));
jButton1.setSize(44, 44);
jButton1.putClientProperty("JButton.buttonType", "roundRect");
jButton1.putClientProperty("JComponent.customArc", 100);
jButton1.putClientProperty("FlatLaf.style", "background: #1B5E20; borderWidth: 0; focusWidth: 0;");

// --- CONFIGURACIÓN PARA EL BOTÓN 2 (Carpeta) ---
jButton2.setPreferredSize(new java.awt.Dimension(42, 42));
jButton2.setSize(42, 42);
jButton2.putClientProperty("JButton.buttonType", "roundRect");
jButton2.putClientProperty("JComponent.customArc", 100);
jButton2.putClientProperty("FlatLaf.style", "background: #1B5E20; borderWidth: 0; focusWidth: 0;");

// --- CONFIGURACIÓN PARA EL BOTÓN 3 (Basura) ---
jButton3.setPreferredSize(new java.awt.Dimension(42, 42));
jButton3.setSize(42, 42);
jButton3.putClientProperty("JButton.buttonType", "roundRect");
jButton3.putClientProperty("JComponent.customArc", 100);
// Asegúrate de que quede EXACTAMENTE así, eliminando cualquier rastro de shadowWidth o shadowOpacity
jButton3.putClientProperty("FlatLaf.style", "background: #EF9FBC; borderWidth: 0; focusWidth: 0;");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        panelredondo1 = new com.mycompany.calis1.panelredondo();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 249, 230));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(1, 181, 226));
        jLabel1.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(27, 94, 32));
        jLabel1.setText("VERDE SMART");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 280, 76));

        jButton1.setBackground(new java.awt.Color(27, 94, 32));
        jButton1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Iniciar sesion");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 266, 44));

        jButton2.setBackground(new java.awt.Color(27, 94, 32));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Crear Cuenta");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 266, 44));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setText("Salir");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 550, 98, 40));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 116, -1, -1));

        javax.swing.GroupLayout panelredondo1Layout = new javax.swing.GroupLayout(panelredondo1);
        panelredondo1.setLayout(panelredondo1Layout);
        panelredondo1Layout.setHorizontalGroup(
            panelredondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        panelredondo1Layout.setVerticalGroup(
            panelredondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        jPanel1.add(panelredondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 87, 230, 230));

        jPanel2.setBackground(new java.awt.Color(27, 94, 32));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new iniciar_sesion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private com.mycompany.calis1.panelredondo panelredondo1;
    // End of variables declaration//GEN-END:variables
}
