/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.calis1;
import java.awt.Image;
import javax.swing.ImageIcon;
/**
 *
 * @author Brith
 */
public class intento extends javax.swing.JPanel {

    /**
     * Creates new form intento
     */
    public intento() {
      initComponents();
        jLabel1.setText("Jardín de Prueba");
        jLabel2.setText("ÁREA: 0 m²");
        jLabel3.setText("Sin plantas");
        
        this.setOpaque(false); 
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 16, 10, 16));
        
        // Ajustamos dimensiones base
        this.setSize(548, 150);
    }
        //this.setBackground(new java.awt.Color(0xCCF9E6));
       // this.putClientProperty("Panel.arc", 15);
    
   public intento(String nombre, String metros, String planta) {
   initComponents();
        
        // 1. OBLIGATORIO: Volvemos el panel transparente para que no dibuje su fondo cuadrado por defecto
        this.setOpaque(false);
        
        // --- CONFIGURACIÓN DE TUS BOTONES ---
        jButton1.setPreferredSize(new java.awt.Dimension(40, 40));
        jButton1.setSize(42, 42);
        jButton1.putClientProperty("FlatLaf.style", "background: #80C1DF; arc: 999; borderWidth: 0; focusWidth: 0;");
        jButton1.setContentAreaFilled(false); 
        jButton1.setBorderPainted(false);     
        jButton1.setFocusPainted(false);      

        jButton2.setPreferredSize(new java.awt.Dimension(42, 42));
        jButton2.setSize(42, 42);
        jButton2.putClientProperty("FlatLaf.style", "background: #7AB06B; arc: 999; borderWidth: 0; focusWidth: 0;");
        jButton2.setContentAreaFilled(false); 
        jButton2.setBorderPainted(false);     
        jButton2.setFocusPainted(false);      

        jButton3.setPreferredSize(new java.awt.Dimension(42, 42));
        jButton3.setSize(42, 42);
        jButton3.setContentAreaFilled(false); 
        jButton3.setBorderPainted(false);     
        jButton3.setFocusPainted(false);      
        jButton3.putClientProperty("FlatLaf.style", "background: #EF9FBC; borderWidth: 0; focusWidth: 0; arc: 999;");

        // Asignar los textos dinámicos
        jLabel1.setText(nombre);
        jLabel2.setText("ÁREA: " + metros + " m²");
        jLabel3.setText(planta);
        
        // Margen interno para que nada toque los bordes curvos
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 16, 12, 16));
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(27, 94, 32));
        jLabel1.setText("jLabel1");

        jLabel2.setForeground(new java.awt.Color(27, 94, 32));
        jLabel2.setText("jLabel2");

        jLabel3.setForeground(new java.awt.Color(27, 94, 32));
        jLabel3.setText("jLabel3");

        jButton1.setBackground(new java.awt.Color(128, 193, 223));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Brith\\Documents\\NetBeansProjects\\calis1\\src\\main\\resources\\imagenes\\gota-de-agua (1).png")); // NOI18N
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Brith\\Documents\\NetBeansProjects\\calis1\\src\\main\\resources\\imagenes\\archivos-y-carpetas.png")); // NOI18N

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Brith\\Documents\\NetBeansProjects\\calis1\\src\\main\\resources\\imagenes\\eliminar (1).png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 389, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
    @Override
    protected void paintComponent(java.awt.Graphics g) {
        java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
        g2.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING, java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(java.awt.Color.WHITE); 
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 25, 25);
        g2.dispose();
        super.paintComponent(g);
    }
}

